name       : kbibtex
version    : 0.8.2
release    : 2
source     :
    - https://download.kde.org/stable/KBibTeX/0.8.2/kbibtex-0.8.2.tar.xz : 081c61c4bb55cf3c88d59877684956df7a235fe80a40a37af92224cdf5d677d6
license    : GPL-2.0-or-later
component  : office
summary    : An editor for bibliographies used with LaTeX
description: |
    The program KBibTeX is a bibliography editor by KDE. Its main purpose is to provide a user-friendly interface to BibTeX files.
builddeps  :
    - pkgconfig(Qt5XmlPatterns)
    - pkgconfig(poppler-qt5)
    - pkgconfig(qca2-qt5)
    - extra-cmake-modules
    - kcrash-devel
    - kdoctools-devel
    - ki18n-devel
    - kiconthemes-devel
    - kparts-devel
    - kwallet-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
