name       : kbibtex
version    : 0.9.2
release    : 11
source     :
    - https://cdn.download.kde.org/stable/KBibTeX/0.9.2/kbibtex-0.9.2.tar.xz : d98651fba99de8ebaf1a19bd8b3c3ac660a34cea33e4c587be30fd61466fac27
license    : GPL-2.0-or-later
component  : office
summary    : An editor for bibliographies used with LaTeX
description: |
    The program KBibTeX is a bibliography editor by KDE. Its main purpose is to provide a user-friendly interface to BibTeX files.
builddeps  :
    - pkgconfig(Qt5NetworkAuth)
    - pkgconfig(Qt5WebEngine)
    - pkgconfig(Qt5WebKit)
    - pkgconfig(Qt5XmlPatterns)
    - pkgconfig(poppler-qt5)
    - pkgconfig(qca2-qt5)
    - extra-cmake-modules
    - kcrash-devel
    - kdoctools-devel
    - ki18n-devel
    - kiconthemes-devel
    - kparts-devel
    - ktexteditor-devel
    - kwallet-devel
    - kwindowsystem-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
