name       : kbibtex
version    : '0.9'
release    : 4
source     :
    - https://download.kde.org/stable/KBibTeX/0.9/kbibtex-0.9.tar.xz : e5d426bb898f801e26655a6a9cc859e63e791229d8d03d1f8b5605860b00460d
license    : GPL-2.0-or-later
component  : office
summary    : An editor for bibliographies used with LaTeX
description: |
    The program KBibTeX is a bibliography editor by KDE. Its main purpose is to provide a user-friendly interface to BibTeX files.
builddeps  :
    - pkgconfig(Qt5NetworkAuth)
    - pkgconfig(Qt5WebEngine)
    - pkgconfig(Qt5WebKit)
    - pkgconfig(Qt5XmlPatterns)
    - pkgconfig(poppler-qt5)
    - pkgconfig(qca2-qt5)
    - extra-cmake-modules
    - kcrash-devel
    - kdoctools-devel
    - ki18n-devel
    - kiconthemes-devel
    - kparts-devel
    - ktexteditor-devel
    - kwallet-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
