name       : kbibtex
version    : 0.9.1
release    : 8
source     :
    - https://cdn.download.kde.org/stable/KBibTeX/0.9.1/kbibtex-0.9.1.tar.xz : 36b1c5b444d70a6b06f4b76bd388611d70300a01a12a9658587b2e11508227ab
license    : GPL-2.0-or-later
component  : office
summary    : An editor for bibliographies used with LaTeX
description: |
    The program KBibTeX is a bibliography editor by KDE. Its main purpose is to provide a user-friendly interface to BibTeX files.
builddeps  :
    - pkgconfig(Qt5NetworkAuth)
    - pkgconfig(Qt5WebEngine)
    - pkgconfig(Qt5WebKit)
    - pkgconfig(Qt5XmlPatterns)
    - pkgconfig(poppler-qt5)
    - pkgconfig(qca2-qt5)
    - extra-cmake-modules
    - kcrash-devel
    - kdoctools-devel
    - ki18n-devel
    - kiconthemes-devel
    - kparts-devel
    - ktexteditor-devel
    - kwallet-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
